version: '3'
services:
  nginx:
    image: nginx
    container_name: 8thwallarandobject
    ports: 
      - "80:80"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
      - ./asserts:/usr/share/nginx/html/asserts
      - ./app.js:/usr/share/nginx/html/app.js
      - ./bottom-circle.css:/usr/share/nginx/html/bottom-circle.css
      - ./bottom-circle.js:/usr/share/nginx/html/bottom-circle.js
